[package]
name = "raknet-node"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
napi = {version="2", features=["async"]}
napi-derive = "2"
tokio = {version = "1.17.0", features = ["full"]}
rust-raknet = { git = "https://github.com/OneRandomOneMe/rust-raknet.git" }

[build-dependencies]
napi-build = "1.2.1"
